'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference.IBlackjackService", SessionMode:=System.ServiceModel.SessionMode.Required)>  _
    Public Interface IBlackjackService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBlackjackService/DealCard", ReplyAction:="http://tempuri.org/IBlackjackService/DealCardResponse")>  _
        Function DealCard() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBlackjackService/Shuffle", ReplyAction:="http://tempuri.org/IBlackjackService/ShuffleResponse")>  _
        Sub Shuffle()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBlackjackService/GetHandValue", ReplyAction:="http://tempuri.org/IBlackjackService/GetHandValueResponse")>  _
        Function GetHandValue(ByVal dealt As String) As Integer
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IBlackjackServiceChannel
        Inherits ServiceReference.IBlackjackService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class BlackjackServiceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference.IBlackjackService)
        Implements ServiceReference.IBlackjackService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function DealCard() As String Implements ServiceReference.IBlackjackService.DealCard
            Return MyBase.Channel.DealCard
        End Function
        
        Public Sub Shuffle() Implements ServiceReference.IBlackjackService.Shuffle
            MyBase.Channel.Shuffle
        End Sub
        
        Public Function GetHandValue(ByVal dealt As String) As Integer Implements ServiceReference.IBlackjackService.GetHandValue
            Return MyBase.Channel.GetHandValue(dealt)
        End Function
    End Class
End Namespace
