'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.21006.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference.IWelcomeSOAPXMLService")>  _
    Public Interface IWelcomeSOAPXMLService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWelcomeSOAPXMLService/Welcome", ReplyAction:="http://tempuri.org/IWelcomeSOAPXMLService/WelcomeResponse")>  _
        Function Welcome(ByVal yourName As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IWelcomeSOAPXMLServiceChannel
        Inherits ServiceReference.IWelcomeSOAPXMLService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WelcomeSOAPXMLServiceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference.IWelcomeSOAPXMLService)
        Implements ServiceReference.IWelcomeSOAPXMLService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Welcome(ByVal yourName As String) As String Implements ServiceReference.IWelcomeSOAPXMLService.Welcome
            Return MyBase.Channel.Welcome(yourName)
        End Function
    End Class
End Namespace
